openapi: 3.0.0
info:
  title: Eecs_ServiceProvisioning
  version: "1.0.1"
  description: |
    API for ECS Service Provisioning.
    © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
    All rights reserved. test

externalDocs:
  description: 3GPP TS 24.558 V17.1.0 Enabling Edge Applications; Protocol specification.
  url: https://www.3gpp.org/ftp/Specs/archive/24_series/24.558/

security:
  - {}
  - oAuth2ClientCredentials: []

servers:
  - url: '{apiRoot}/eecs-serviceprovisioning/v1'
    variables:
      apiRoot:
        default: https://example.com
        description: apiRoot as defined in clause 7.5 of 3GPP TS 29.558

paths:
  /subscriptions:
    post:
      description: >
        Creates a new subscription in ECS in order to be notified of provisioning data 
        changes of interest.
      tags:
        - Service Provisioning Subscriptions
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ECSServProvSubscription'
      callbacks:
        notificationDestination:
          '{request.body#/notificationDestination}':
            post:
              requestBody:  # contents of the callback message
                required: true
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/ServProvNotification'
              responses:
                '204':
                  description: No Content (successful notification)
                '307':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/307'
                '308':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/308'
                '400':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/400'
                '401':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/401'
                '403':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/403'
                '404':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/404'
                '411':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/411'
                '413':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/413'
                '415':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/415'
                '429':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/429'
                '500':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/500'
                '503':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/503'
                default:
                  $ref: 'TS29122_CommonData.yaml#/components/responses/default'
      responses:
        '201':
          description: >
            Individual ECS Service Provisioning Subscription resource created successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ECSServProvSubscription'
          headers:
            Location:
              description: 'Contains the URI of the newly created resource'
              required: true
              schema:
                type: string
        '400':
          $ref: 'TS29122_CommonData.yaml#/components/responses/400'
        '401':
          $ref: 'TS29122_CommonData.yaml#/components/responses/401'
        '403':
          $ref: 'TS29122_CommonData.yaml#/components/responses/403'
        '404':
          $ref: 'TS29122_CommonData.yaml#/components/responses/404'
        '411':
          $ref: 'TS29122_CommonData.yaml#/components/responses/411'
        '413':
          $ref: 'TS29122_CommonData.yaml#/components/responses/413'
        '415':
          $ref: 'TS29122_CommonData.yaml#/components/responses/415'
        '429':
          $ref: 'TS29122_CommonData.yaml#/components/responses/429'
        '500':
          $ref: 'TS29122_CommonData.yaml#/components/responses/500'
        '503':
          $ref: 'TS29122_CommonData.yaml#/components/responses/503'
        default:
          $ref: 'TS29122_CommonData.yaml#/components/responses/default'

  /subscriptions/{subscriptionId}:
    put:
      description: >
        Updates an existing individual service provisioning subscription identified
        by the subscriptionId.
      tags:
        - Individual Service Provisioning Subscription
      parameters:
        - name: subscriptionId
          in: path
          description: Identifies an individual service provisioning subscription
          required: true
          schema:
            type: string
      requestBody:
        description: Parameters to replace the existing subscription
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ECSServProvSubscription'
      responses:
        '200':
          description: >
            OK (The individual service provisioning subscription matching the subscriptionId
            was modified successfully).
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ECSServProvSubscription'
        '400':
          $ref: 'TS29122_CommonData.yaml#/components/responses/400'
        '401':
          $ref: 'TS29122_CommonData.yaml#/components/responses/401'
        '403':
          $ref: 'TS29122_CommonData.yaml#/components/responses/403'
        '404':
          $ref: 'TS29122_CommonData.yaml#/components/responses/404'
        '411':
          $ref: 'TS29122_CommonData.yaml#/components/responses/411'
        '413':
          $ref: 'TS29122_CommonData.yaml#/components/responses/413'
        '415':
          $ref: 'TS29122_CommonData.yaml#/components/responses/415'
        '429':
          $ref: 'TS29122_CommonData.yaml#/components/responses/429'
        '500':
          $ref: 'TS29122_CommonData.yaml#/components/responses/500'
        '503':
          $ref: 'TS29122_CommonData.yaml#/components/responses/503'
        default:
          $ref: 'TS29122_CommonData.yaml#/components/responses/default'

    delete:
      description: >
        Deletes an existing individual service provisioning subscription identified by
        the subscriptionId.
      tags:
        - Individual Service Provisioning Subscription
      parameters:
        - name: subscriptionId
          in: path
          description: Identifies an individual service provisioning subscription
          required: true
          schema:
            type: string
      responses:
        '204':
          description: >
            The individual service provisioning subscription matching the subscriptionId is
            deleted.
        '307':
          $ref: 'TS29122_CommonData.yaml#/components/responses/307'
        '308':
          $ref: 'TS29122_CommonData.yaml#/components/responses/308'
        '400':
          $ref: 'TS29122_CommonData.yaml#/components/responses/400'
        '401':
          $ref: 'TS29122_CommonData.yaml#/components/responses/401'
        '403':
          $ref: 'TS29122_CommonData.yaml#/components/responses/403'
        '404':
          $ref: 'TS29122_CommonData.yaml#/components/responses/404'
        '429':
          $ref: 'TS29122_CommonData.yaml#/components/responses/429'
        '500':
          $ref: 'TS29122_CommonData.yaml#/components/responses/500'
        '503':
          $ref: 'TS29122_CommonData.yaml#/components/responses/503'
        default:
          $ref: 'TS29122_CommonData.yaml#/components/responses/default'
    patch:
      description: >
        Partially updates an existing individual service provisioning subscription identified
        by the subscriptionId.
      tags:
        - Individual Service Provisioning Subscription
      parameters:
        - name: subscriptionId
          in: path
          description: Identifies an individual service provisioning subscription
          required: true
          schema:
            type: string
      requestBody:
        description: Parameters to replace the existing subscription
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ECSServProvSubscriptionPatch'
      responses:
        '200':
          description: >
            OK (The individual service provisioning subscription matching the subscriptionId
            was modified successfully)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ECSServProvSubscription'
        '400':
          $ref: 'TS29122_CommonData.yaml#/components/responses/400'
        '401':
          $ref: 'TS29122_CommonData.yaml#/components/responses/401'
        '403':
          $ref: 'TS29122_CommonData.yaml#/components/responses/403'
        '404':
          $ref: 'TS29122_CommonData.yaml#/components/responses/404'
        '411':
          $ref: 'TS29122_CommonData.yaml#/components/responses/411'
        '413':
          $ref: 'TS29122_CommonData.yaml#/components/responses/413'
        '415':
          $ref: 'TS29122_CommonData.yaml#/components/responses/415'
        '429':
          $ref: 'TS29122_CommonData.yaml#/components/responses/429'
        '500':
          $ref: 'TS29122_CommonData.yaml#/components/responses/500'
        '503':
          $ref: 'TS29122_CommonData.yaml#/components/responses/503'
        default:
          $ref: 'TS29122_CommonData.yaml#/components/responses/default'

  /request:
    post:
      summary: Request service provisioning information.
      operationId: RequestServProv
      tags:
        - Request Service Provisioning
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ECSServProvReq'
      responses:
        '200':
          description: >
            OK (The requested service provisioning information was returned successfully).
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ECSServProvResp'
        '204':
          description: >
            No Content (the requested service provisioning information does not exist).
        '400':
          $ref: 'TS29122_CommonData.yaml#/components/responses/400'
        '401':
          $ref: 'TS29122_CommonData.yaml#/components/responses/401'
        '403':
          $ref: 'TS29122_CommonData.yaml#/components/responses/403'
        '404':
          $ref: 'TS29122_CommonData.yaml#/components/responses/404'
        '411':
          $ref: 'TS29122_CommonData.yaml#/components/responses/411'
        '413':
          $ref: 'TS29122_CommonData.yaml#/components/responses/413'
        '415':
          $ref: 'TS29122_CommonData.yaml#/components/responses/415'
        '429':
          $ref: 'TS29122_CommonData.yaml#/components/responses/429'
        '500':
          $ref: 'TS29122_CommonData.yaml#/components/responses/500'
        '503':
          $ref: 'TS29122_CommonData.yaml#/components/responses/503'
        default:
          $ref: 'TS29122_CommonData.yaml#/components/responses/default'

components:
  securitySchemes:
    oAuth2ClientCredentials:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: '{tokenUrl}'
          scopes: {}
  schemas:
    ECSServProvReq:
      description: ECS service provisioning request information.
      type: object
      properties:
        eecId:
          type: string
          description: Represents a unique identifier of the EEC.
        ueId:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/Gpsi'
        acProfs:
          type: array
          items:
            $ref: 'TS24558_Eees_EECRegistration.yaml#/components/schemas/ACProfile'
          description: Information about services the EEC wants to connect to.
        eecSvcContSupp:
          type: array
          items:
            $ref: 'TS29558_Eecs_EESRegistration.yaml#/components/schemas/ACRScenario'
          description: >
            Indicates if the EEC supports service continuity or not, also indicates which
            ACR scenarios are supported by the EEC.
        connInfo:
          type: array
          items:
            $ref: '#/components/schemas/ConnectivityInfo'
          description: List of connectivity information for the UE.
        locInf:
          $ref: 'TS29122_MonitoringEvent.yaml#/components/schemas/LocationInfo'
      required:
        - eecId
    ECSServProvResp:
      description: ECS service provisioning response information.
      type: object
      properties:
        ednCnfgInfo:
          type: array
          items:
            $ref: '#/components/schemas/EDNConfigInfo'
          minItems: 1
          description: List of EDN configuration information.
      required:
        - ednCnfgInfo
    ECSServProvSubscription:
      description: Represents an individual service provisioning subscription resource.
      type: object
      properties:
        eecId:
          type: string
          description: Represents a unique identifier of the EEC.
        ueId:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/Gpsi'
        acProfs:
          type: array
          items:
            $ref: 'TS24558_Eees_EECRegistration.yaml#/components/schemas/ACProfile'
          description: Information about services the EEC wants to connect to.
        expTime:
          $ref: 'TS29122_CommonData.yaml#/components/schemas/DateTime'
        eecSvcContSupp:
          type: array
          items:
            $ref: 'TS29558_Eecs_EESRegistration.yaml#/components/schemas/ACRScenario'
          description: >
            Indicates if the EEC supports service continuity or not, also indicates which
            ACR scenarios are supported by the EEC.
        connInfo:
          type: array
          items:
            $ref: '#/components/schemas/ConnectivityInfo'
          description: List of connectivity information for the UE.
        notificationDestination:
          $ref: 'TS29122_CommonData.yaml#/components/schemas/Uri'
        requestTestNotification:
          type: boolean
          description: >
            Set to true by Subscriber to request the ECS to send a test notification. Set to 
            false or omitted otherwise.
        websockNotifConfig:
          $ref: 'TS29122_CommonData.yaml#/components/schemas/WebsockNotifConfig'
        suppFeat:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/SupportedFeatures'
      required:
        - eecId
    ServProvNotification:
      description: Represents notification information of a service provisioning Event.
      type: object
      properties:
        subId:
          type: string
          description: >
            Identifier of the individual service provisioning subscription for which the service
            provisioning notification is delivered.
        ednCnfgInfo:
          type: array
          items:
            $ref: '#/components/schemas/EDNConfigInfo'
          minItems: 1
          description: List of EDN configuration information.
      required:
        - subId
        - ednCnfgInfo
    ConnectivityInfo:
      description: Represents the connectivity information for the UE.
      type: object
      properties:
        plmnId:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/PlmnId'
        ssId:
          type: string
          description: Identifies the SSID of the access point to which the UE is attached.
    EDNConfigInfo:
      description: Represents the EDN information.
      type: object
      properties:
        ednConInfo:
          $ref: '#/components/schemas/EDNConInfo'
        eess:
          type: array
          items:
            $ref: '#/components/schemas/EESInfo'
          minItems: 1
          description: Contains the list of EESs of the EDN.
        lifeTime:
          $ref: 'TS29122_CommonData.yaml#/components/schemas/DateTime'
      required:
        - ednConInfo
        - eess
    EDNConInfo:
      description: Represents an EDN connection information .
      type: object
      properties:
        dnn:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/Dnn'
        snssai:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/Snssai'
        ednTopoSrvArea:
          $ref: 'TS29122_CommonData.yaml#/components/schemas/LocationArea5G'
    EESInfo:
      description: Represents EES information.
      type: object
      properties:
        eesId:
          type: string
          description: Identity of the EES
        endPt:
          $ref: 'TS29558_Eees_EASRegistration.yaml#/components/schemas/EndPoint' 
        easIds:
          type: array
          items:
            type: string
          description: Application identities of the Edge Application Servers registered with the EES.
        ecspInfo:
          type: string
          description: Represents an ECSP Information.
        svcArea:
          $ref: 'TS29122_CommonData.yaml#/components/schemas/LocationArea5G'
        dnais:
          type: array
          items:
            $ref: 'TS29571_CommonData.yaml#/components/schemas/Dnai'
          description: Represents list of Data network access identifier.
        eesSvcContSupp:
          type: array
          items:
            $ref: 'TS29558_Eecs_EESRegistration.yaml#/components/schemas/ACRScenario'
          description: >
            Indicates if the EES supports service continuity or not, also indicates which ACR
            scenarios are supported by the EES.
        eecRegConf:
          type: boolean
          description: >
            Indicates whether the EEC is required to register on the EES to use edge services
            or not.
      required:
        - eesId
        - eecRegConf
    ECSServProvSubscriptionPatch:
      description: Represents an individual service provisioning subscription resource.
      type: object
      properties:
        acProfs:
          type: array
          items:
            $ref: 'TS24558_Eees_EECRegistration.yaml#/components/schemas/ACProfile'
          description: Information about services the EEC wants to connect to.
        expTime:
          $ref: 'TS29122_CommonData.yaml#/components/schemas/DateTime'
        eecSvcContSupp:
          type: array
          items:
            $ref: 'TS29558_Eecs_EESRegistration.yaml#/components/schemas/ACRScenario'
          description: >
            Indicates if the EEC supports service continuity or not, also indicates which ACR
            scenarios are supported by the EEC.
        connInfo:
          type: array
          items:
            $ref: '#/components/schemas/ConnectivityInfo'
          description: List of connectivity information for the UE.
