openapi: 3.0.1
info:
  title: MDA Report
  version: 17.6.0
  description: >-
    OAS 3.0.1 specification of the MDA Report
    © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
    All rights reserved.
externalDocs:
  description: 3GPP TS 28.104; MDA Report
  url: http://www.3gpp.org/ftp/Specs/archive/28_series/28.104/
paths: {}
components:
  schemas:

#-------- Definition of types-----------------------------------------------------

    MDAOutputs:
      type: object
      properties:
        mDAType:
          type: string
        mDAOutputList:
          type: array
          items:
            $ref: '#/components/schemas/MDAOutputEntry'
        mDARequestRef:
          $ref: 'TS28623_ComDefs.yaml#/components/schemas/Dn'
        analyticsWindow:
          $ref: '#/components/schemas/TimeWindow'
        confidenceDegree:
          type: number
          format: float

    MDAOutputEntry:
      type: object
      properties:
        mDAOutputIEName:
          type: string
        mDAOutputIEValue: {}


    TimeWindow:
      type: object
      properties:
        mDAOutputStartTime:
          $ref: 'TS28623_ComDefs.yaml#/components/schemas/DateTime'
        mDAOutputEndTime:
          $ref: 'TS28623_ComDefs.yaml#/components/schemas/DateTime'


#-------- Definition of MDA Report --------------------------------------------

    MDAReport:
      allOf:
        - $ref: 'TS28623_GenericNrm.yaml#/components/schemas/Top'
        - type: object
          properties:
            attributes:
              allOf:
                - type: object
                  properties:
                    mDAReportID:
                      type: string
                    mDAOutputs:
                      $ref: '#/components/schemas/MDAOutputs'
