openapi: 3.0.0

info:
  version: '1.0.1'
  title: 'Nhss_SDM'
  description: |
    HSS Subscriber Data Management.
    © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
    All rights reserved.

externalDocs:
  description: 3GPP TS 29.563 HSS Services for Interworking With UDM, version 16.3.0
  url: 'http://www.3gpp.org/ftp/Specs/archive/29_series/29.563/'

servers:
  - url: '{apiRoot}/nhss-sdm/v1'
    variables:
      apiRoot:
        default: https://example.com
        description: apiRoot as defined in clause 4.4 of 3GPP TS 29.501.

security:
  - oAuth2ClientCredentials:
    - nhss-sdm
  - {}

paths:
  /{ueId}/ue-context-in-pgw-data:
    get:
      summary: Retrieve the UE Context In PGW
      operationId: GetUeCtxInPgwData
      tags:
        - UE Context In PGW Data Retrieval
      parameters:
        - name: ueId
          in: path
          description: Identifier of the UE
          required: true
          schema:
            type: string
            pattern: '^(imsi-[0-9]{5,15})$'
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UeContextInPgwData'
        '400':
          $ref: 'TS29571_CommonData.yaml#/components/responses/400'
        '404':
          $ref: 'TS29571_CommonData.yaml#/components/responses/404'
        '500':
          $ref: 'TS29571_CommonData.yaml#/components/responses/500'
        '503':
          $ref: 'TS29571_CommonData.yaml#/components/responses/503'
        default:
          description: Unexpected error

  /{ueId}/subscriptions:
    post:
      summary: subscribe to notifications
      operationId: Subscribe
      tags:
        - Subscription Creation
      parameters:
        - name: ueId
          in: path
          description: IMSI of the user
          required: true
          schema:
            type: string
            pattern: '^(imsi-[0-9]{5,15})$'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubscriptionData'
        required: true
      responses:
        '201':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubscriptionData'
          headers:
            Location:
              description: 'Contains the URI of the newly created resource, according to the structure: {apiRoot}/nhss-sdm/<apiVersion>/{ueId}/subscriptions/{subscriptionId}'
              required: true
              schema:
                type: string
        '400':
          $ref: 'TS29571_CommonData.yaml#/components/responses/400'
        '404':
          $ref: 'TS29571_CommonData.yaml#/components/responses/404'
        '500':
          $ref: 'TS29571_CommonData.yaml#/components/responses/500'
        '501':
          $ref: 'TS29571_CommonData.yaml#/components/responses/501'
        '503':
          $ref: 'TS29571_CommonData.yaml#/components/responses/503'
        default:
          description: Unexpected error
      callbacks:
        datachangeNotification:
          '{request.body#/callbackReference}':
            post:
              requestBody:
                required: true
                content:
                  application/json:
                    schema:
                      $ref: 'TS29503_Nudm_SDM.yaml#/components/schemas/ModificationNotification'
              responses:
                '204':
                  description: Successful Notification response
                '400':
                  $ref: 'TS29571_CommonData.yaml#/components/responses/400'
                '404':
                  $ref: 'TS29571_CommonData.yaml#/components/responses/404'
                '500':
                  $ref: 'TS29571_CommonData.yaml#/components/responses/500'
                '503':
                  $ref: 'TS29571_CommonData.yaml#/components/responses/503'
                default:
                  description: Unexpected error

  /{ueId}/subscriptions/{subscriptionId}:
    delete:
      summary: unsubscribe from notifications
      operationId: Unsubscribe
      tags:
        - Subscription Deletion
      parameters:
        - name: ueId
          in: path
          description: IMSI of the user
          required: true
          schema:
            type: string
            pattern: '^(imsi-[0-9]{5,15})$'
        - name: subscriptionId
          in: path
          description: Id of the Subscription
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Successful response
        '400':
          $ref: 'TS29571_CommonData.yaml#/components/responses/400'
        '404':
          $ref: 'TS29571_CommonData.yaml#/components/responses/404'
        '500':
          $ref: 'TS29571_CommonData.yaml#/components/responses/500'
        '503':
          $ref: 'TS29571_CommonData.yaml#/components/responses/503'
        default:
          description: Unexpected error
    patch:
      summary: modify the subscription
      operationId: Modify
      tags:
        - Subscription Modification
      parameters:
        - name: ueId
          in: path
          description: IMSI of the user
          required: true
          schema:
            type: string
            pattern: '^(imsi-[0-9]{5,15})$'
        - name: subscriptionId
          in: path
          description: Id of the Subscription
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json-patch+json:
            schema:
              type: array
              items:
                $ref: 'TS29571_CommonData.yaml#/components/schemas/PatchItem'
              minItems: 1
        required: true
      responses:
        '204':
          description: Successful modification
        '400':
          $ref: 'TS29571_CommonData.yaml#/components/responses/400'
        '403':
          $ref: 'TS29571_CommonData.yaml#/components/responses/403'
        '404':
          $ref: 'TS29571_CommonData.yaml#/components/responses/404'
        '500':
          $ref: 'TS29571_CommonData.yaml#/components/responses/500'
        '503':
          $ref: 'TS29571_CommonData.yaml#/components/responses/503'
        default:
          description: Unexpected error

components:
  securitySchemes:
    oAuth2ClientCredentials:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: '{nrfApiRoot}/oauth2/token'
          scopes:
            nhss-sdm: Access to the nhss-sdm API


  schemas:

# COMPLEX TYPES:

    UeContextInPgwData:
      type: object
      properties:
        pgwInfo:
          type: array
          items:
            $ref: 'TS29503_Nudm_SDM.yaml#/components/schemas/PgwInfo'
          minItems: 1
        emergencyFqdn:
          type: string

    SubscriptionData:
      type: object
      required:
        - nfInstanceId
        - callbackReference
        - monitoredResourceUris
      properties:
        nfInstanceId:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/NfInstanceId'
        callbackReference:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/Uri'
        monitoredResourceUris:
          type: array
          items:
            $ref: 'TS29571_CommonData.yaml#/components/schemas/Uri'
          minItems: 1
        expires:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/DateTime'
        immediateReport:
          type: boolean
          default: false
        report:
          $ref: '#/components/schemas/SubscriptionDataSets'

    SubscriptionDataSets:
      type: object
      properties:
        ueContextInPgwData:
          $ref: '#/components/schemas/UeContextInPgwData'

# SIMPLE TYPES:


# ENUMS:
