openapi: 3.0.0
info:
  title: ECS EES Registration_API
  description: |
    API for EES Registration.
    © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
    All rights reserved.
  version: 1.0.0-alpha.2
externalDocs:
  description: 3GPP TS 29.558 V1.2.0 Enabling Edge Applications; Application Programming Interface (API) specification; Stage 3
  url: http://www.3gpp.org/ftp/Specs/archive/29_series/29.558/
servers:
  - url: '{apiRoot}/eecs-eesregistration/v1'
    variables:
      apiRoot:
        default: https://example.com
        description: apiRoot as defined in clause 7.5 of 3GPP TS 29.558.

paths:
  /registrations:
    post:
      description: Registers a new EES at the Edge Configuration Server.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EESRegistration'
      responses:
        '201':
          description: EES information is registered successfully at ECS.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EESRegistration'
          headers:
            Location:
              description: 'Contains the URI of the newly created resource'
              required: true
              schema:
                type: string
        '400':
          $ref: 'TS29122_CommonData.yaml#/components/responses/400'
        '401':
          $ref: 'TS29122_CommonData.yaml#/components/responses/401'
        '403':
          $ref: 'TS29122_CommonData.yaml#/components/responses/403'
        '404':
          $ref: 'TS29122_CommonData.yaml#/components/responses/404'
        '411':
          $ref: 'TS29122_CommonData.yaml#/components/responses/411'
        '413':
          $ref: 'TS29122_CommonData.yaml#/components/responses/413'
        '415':
          $ref: 'TS29122_CommonData.yaml#/components/responses/415'
        '429':
          $ref: 'TS29122_CommonData.yaml#/components/responses/429'
        '500':
          $ref: 'TS29122_CommonData.yaml#/components/responses/500'
        '503':
          $ref: 'TS29122_CommonData.yaml#/components/responses/503'
        default:
          $ref: 'TS29122_CommonData.yaml#/components/responses/default'

  /registrations/{registrationId}:
    get:
      description: Retrieve an Individual EES registration resource.
      parameters:
        - name: registrationId
          in: path
          description: Registration Id.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK (The EES registration information at the Edge Configuration Server).
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EESRegistration'
        '400':
          $ref: 'TS29122_CommonData.yaml#/components/responses/400'
        '401':
          $ref: 'TS29122_CommonData.yaml#/components/responses/401'
        '403':
          $ref: 'TS29122_CommonData.yaml#/components/responses/403'
        '404':
          $ref: 'TS29122_CommonData.yaml#/components/responses/404'
        '406':
          $ref: 'TS29122_CommonData.yaml#/components/responses/406'
        '429':
          $ref: 'TS29122_CommonData.yaml#/components/responses/429'
        '500':
          $ref: 'TS29122_CommonData.yaml#/components/responses/500'
        '503':
          $ref: 'TS29122_CommonData.yaml#/components/responses/503'
        default:
          $ref: 'TS29122_CommonData.yaml#/components/responses/default'
    put:
      description: Fully replace an existing EES Registration resource.
      parameters:
        - name: registrationId
          in: path
          description: EES Registration Id.
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EESRegistration'
      responses:
        '200':
          description: OK (The EES registration information is updated successfully).
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EESRegistration'
        '204':
          description: No Content. The individual EES registration information is updated successfully.
        '400':
          $ref: 'TS29122_CommonData.yaml#/components/responses/400'
        '401':
          $ref: 'TS29122_CommonData.yaml#/components/responses/401'
        '403':
          $ref: 'TS29122_CommonData.yaml#/components/responses/403'
        '404':
          $ref: 'TS29122_CommonData.yaml#/components/responses/404'
        '411':
          $ref: 'TS29122_CommonData.yaml#/components/responses/411'
        '413':
          $ref: 'TS29122_CommonData.yaml#/components/responses/413'
        '415':
          $ref: 'TS29122_CommonData.yaml#/components/responses/415'
        '429':
          $ref: 'TS29122_CommonData.yaml#/components/responses/429'
        '500':
          $ref: 'TS29122_CommonData.yaml#/components/responses/500'
        '503':
          $ref: 'TS29122_CommonData.yaml#/components/responses/503'
        default:
          $ref: 'TS29122_CommonData.yaml#/components/responses/default'
    patch:
      description: Partially update an existing EES Registration resource.
      parameters:
        - name: registrationId
          in: path
          description: EES registration Id.
          required: true
          schema:
            type: string
      requestBody:
        description: Partial update an existing EES registration resource.
        required: true
        content:
          application/merge-patch+json:
            schema:
              $ref: '#/components/schemas/EESRegistrationPatch'
      responses:
        '200':
          description: The Individual EES registration is successfully modified and the updated registration information is returned in the response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EESRegistration'
        '204':
          description: No Content. The individual EES registration information is updated successfully.
        '400':
          $ref: 'TS29122_CommonData.yaml#/components/responses/400'
        '401':
          $ref: 'TS29122_CommonData.yaml#/components/responses/401'
        '403':
          $ref: 'TS29122_CommonData.yaml#/components/responses/403'
        '404':
          $ref: 'TS29122_CommonData.yaml#/components/responses/404'
        '411':
          $ref: 'TS29122_CommonData.yaml#/components/responses/411'
        '413':
          $ref: 'TS29122_CommonData.yaml#/components/responses/413'
        '415':
          $ref: 'TS29122_CommonData.yaml#/components/responses/415'
        '429':
          $ref: 'TS29122_CommonData.yaml#/components/responses/429'
        '500':
          $ref: 'TS29122_CommonData.yaml#/components/responses/500'
        '503':
          $ref: 'TS29122_CommonData.yaml#/components/responses/503'
        default:
          $ref: 'TS29122_CommonData.yaml#/components/responses/default'
    delete:
      description: Delete an existing EES registration at ECS.
      parameters:
        - name: registrationId
          in: path
          description: Registration Id.
          required: true
          schema:
            type: string
      responses:
        '204':
          description: The individual EES registration is deleted.
        '400':
          $ref: 'TS29122_CommonData.yaml#/components/responses/400'
        '401':
          $ref: 'TS29122_CommonData.yaml#/components/responses/401'
        '403':
          $ref: 'TS29122_CommonData.yaml#/components/responses/403'
        '404':
          $ref: 'TS29122_CommonData.yaml#/components/responses/404'
        '429':
          $ref: 'TS29122_CommonData.yaml#/components/responses/429'
        '500':
          $ref: 'TS29122_CommonData.yaml#/components/responses/500'
        '503':
          $ref: 'TS29122_CommonData.yaml#/components/responses/503'
        default:
          $ref: 'TS29122_CommonData.yaml#/components/responses/default'

components:
  schemas:
    EESRegistration:
      type: object
      description: Represents an EES registration information.
      properties:
        eesProf:
          $ref: '#/components/schemas/EESProfile'
        expTime:
          $ref: 'TS29122_CommonData.yaml#/components/schemas/DateTime'
        suppFeat:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/SupportedFeatures'
      required:
        - eesProf
    EESProfile:
      type: object
      description: Represents the EES profile information.
      properties:
        eesId:
          type: string
          description: Identifier of the EES.
        endPt:
          $ref: 'TS29558_Eees_EASRegistration.yaml#/components/schemas/EndPoint'
        easIds:
          type: array
          items:
            type: string
          minItems: 1
          description: Identities of EASs that are registered with EES.
        provId:
          type: string
          description: Identifier of the ECSP that provides the EES provider.
        svcArea:
          $ref: '#/components/schemas/ServiceArea'
        appLocs:
          type: array
          items:
            $ref: 'TS29571_CommonData.yaml#/components/schemas/Dnai'
          minItems: 1
          description: List of DNAI(s) associated with the EES.
        svcContSupp:
          type: array
          items:
            $ref: '#/components/schemas/ACRScenario'
          minItems: 1
          description: The ACR scenarios supported by the EES for service continuity.
        eecRegConf:
          type: boolean
          description: Set to true if the EEC is required to register to the EES to use edge service. Set to false if the EEC is not required to register to use edge services.
      required:
        - eesId
        - endPt
        - eecRegConf
    EESRegistrationPatch:
      type: object
      description: Represents partial update request of individual EES registration information.
      properties:
        eesProf:
          $ref: '#/components/schemas/EESProfile'
        expTime:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/DateTimeRm'
    ServiceArea:
      type: object
      description: Represents a service area information of the EdgeApp entity.
      properties:
        topServAr:
          $ref: '#/components/schemas/TopologicalServiceArea'
        geoServAr:
          $ref: '#/components/schemas/GeographicalServiceArea'
    TopologicalServiceArea:
      type: object
      description: Represents topological service area information.
      properties:
        ecgis:
          type: array
          items:
            $ref: 'TS29571_CommonData.yaml#/components/schemas/Ecgi'
          minItems: 1
          description: A list of E-UTRA cell identities.
        ncgis:
          type: array
          items:
            $ref: 'TS29571_CommonData.yaml#/components/schemas/Ncgi'
          minItems: 1
          description: A list of NR cell identities.
        tais:
          type: array
          items:
            $ref: 'TS29571_CommonData.yaml#/components/schemas/Tai'
          minItems: 1
          description: A list of tracking area identities.
        plmnIds:
          type: array
          items:
            $ref: 'TS29122_CommonData.yaml#/components/schemas/PlmnId'
          minItems: 1
          description: A list of PLMN identities.
    GeographicalServiceArea:
      type: object
      description: Represents geographical service area information.
      properties:
        geoArs:
          type: array
          items:
            $ref: 'TS29572_Nlmf_Location.yaml#/components/schemas/GeographicArea'
          minItems: 1
          description: A list of geographic area information.
        civicAddrs:
          type: array
          items:
            $ref: 'TS29572_Nlmf_Location.yaml#/components/schemas/CivicAddress'
          minItems: 1
          description: A list of civic address information.
    ACRScenario:
      anyOf:
      - type: string
        enum:
          - EEC_INITIATED
          - EEC_EXECUTED_VIA_SOURCE_EES
          - EEC_EXECUTED_VIA_TARGET_EES
          - SOURCE_EAS_DECIDED
          - SOURCE_EES_EXECUTED
          - EEL_MANAGED_ACR
      - type: string
        description: >
          This string provides forward-compatibility with future
          extensions to the enumeration but is not used to encode
          content defined in the present version of this API.
      description: >
        Possible values are
        - EEC_INITIATED: Represents the EEC initiated ACR scenario.
        - EEC_EXECUTED_VIA_SOURCE_EES: Represents the EEC ACR scenario executed via the S-EES.
        - EEC_EXECUTED_VIA_TARGET_EES: Represents the EEC ACR scenario executed via the T-EES.
        - SOURCE_EAS_DECIDED: Represents the EEC ACR scenario where the S-EAS decides to perform ACR.
        - SOURCE_EES_EXECUTED: Represents the EEC ACR scenario where S-EES executes the ACR.
        - EEL_MANAGED_ACR: Represents the EEC ACR scenario where the ACR is managed by the Edge Enabler Layer.
