openapi: 3.0.0

info:
  version: '1.0.1'
  title: 'Nhss_EE'
  description: |
    HSS Event Exposure
    © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
    All rights reserved.

externalDocs:
  description: 3GPP TS 29.563 HSS Services for Interworking With UDM, version 16.2.0
  url: 'http://www.3gpp.org/ftp/Specs/archive/29_series/29.563/'

servers:
  - url: '{apiRoot}/nhss-ee/v1'
    variables:
      apiRoot:
        default: https://example.com
        description: apiRoot as defined in clause 4.4 of 3GPP TS 29.501.

security:
  - {}
  - oAuth2ClientCredentials:
    - nhss-ee

paths:
  /{ueId}/ee-subscriptions:
    post:
      summary: Subscribe
      operationId: CreateEeSubscription
      tags:
        - EE Subscription (Collection)
      parameters:
        - name: ueId
          in: path
          description: IMSI of the subscriber
          required: true
          schema:
            $ref: '#/components/schemas/Imsi'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EeSubscription'
        required: true
      responses:
        '201':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreatedEeSubscription'
          headers:
            Location:
              description: 'Contains the URI of the newly created resource, according to the structure: {apiRoot}/nhss-ee/v1/{ueId}/ee-subscriptions/{subscriptionId}'
              required: true
              schema:
                type: string
        '400':
          $ref: 'TS29571_CommonData.yaml#/components/responses/400'
        '403':
          $ref: 'TS29571_CommonData.yaml#/components/responses/403'
        '404':
          $ref: 'TS29571_CommonData.yaml#/components/responses/404'
        '500':
          $ref: 'TS29571_CommonData.yaml#/components/responses/500'
        '501':
          $ref: 'TS29571_CommonData.yaml#/components/responses/501'
        '503':
          $ref: 'TS29571_CommonData.yaml#/components/responses/503'
        default:
          description: Unexpected error
      callbacks:
        eventOccurrenceNotification:
          '{request.body#/callbackReference}':
            post:
              requestBody:
                required: true
                content:
                  application/json:
                    schema:
                      type: array
                      items:
                        $ref: '#/components/schemas/MonitoringReport'
                      minItems: 1
              responses:
                '204':
                  description: Successful Notification response
                '400':
                  $ref: 'TS29571_CommonData.yaml#/components/responses/400'
                '404':
                  $ref: 'TS29571_CommonData.yaml#/components/responses/404'
                '500':
                  $ref: 'TS29571_CommonData.yaml#/components/responses/500'
                '503':
                  $ref: 'TS29571_CommonData.yaml#/components/responses/503'
                default:
                  description: Unexpected error

  /{ueId}/ee-subscriptions/{subscriptionId}:
    delete:
      summary: Unsubscribe
      operationId: DeleteEeSubscription
      tags:
        - Delete EE Subscription
      parameters:
        - name: ueId
          in: path
          description: IMSI of the subscriber
          required: true
          schema:
            $ref: '#/components/schemas/Imsi'
        - name: subscriptionId
          in: path
          description: Id of the EE Subscription
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Successful response
        '400':
          $ref: 'TS29571_CommonData.yaml#/components/responses/400'
        '404':
          $ref: 'TS29571_CommonData.yaml#/components/responses/404'
        '500':
          $ref: 'TS29571_CommonData.yaml#/components/responses/500'
        '503':
          $ref: 'TS29571_CommonData.yaml#/components/responses/503'
        default:
          description: Unexpected error
    patch:
      summary: Patch
      operationId: UpdateEeSubscription
      tags:
        - Update EE Subscription
      parameters:
        - name: ueId
          in: path
          description: IMSI of the subscriber
          required: true
          schema:
            $ref: '#/components/schemas/Imsi'
        - name: subscriptionId
          in: path
          description: Id of the EE Subscription
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json-patch+json:
            schema:
              type: array
              items:
                $ref: 'TS29571_CommonData.yaml#/components/schemas/PatchItem'
              minItems: 1
        required: true
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: 'TS29571_CommonData.yaml#/components/schemas/PatchResult'
        '204':
          description: Successful response
        '403':
          $ref: 'TS29571_CommonData.yaml#/components/responses/403'
        '404':
          $ref: 'TS29571_CommonData.yaml#/components/responses/404'
        default:
          description: Unexpected error

components:
  securitySchemes:
    oAuth2ClientCredentials:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: '{nrfApiRoot}/oauth2/token'
          scopes:
            nhss-ee: Access to the nhss-ee API

  schemas:

# COMPLEX TYPES:

    EeSubscription:
      type: object
      required:
        - callbackReference
      properties:
        callbackReference:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/Uri'
        scefId:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/DiameterIdentity'
        monitoringConfigurations:
          description: A map (list of key-value pairs where ReferenceId serves as key) of MonitoringConfigurations
          type: object
          additionalProperties:
            $ref: '#/components/schemas/MonitoringConfiguration'
          minProperties: 1
        supportedFeatures:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/SupportedFeatures'
        reportingOptions:
          $ref: '#/components/schemas/ReportingOptions'

    CreatedEeSubscription:
      type: object
      required:
        - eeSubscription
      properties:
        eeSubscription:
            $ref: '#/components/schemas/EeSubscription'
        eventReports:
          type: array
          items:
            $ref: '#/components/schemas/MonitoringReport'
          minItems: 1

    MonitoringConfiguration:
      type: object
      required:
        - eventType
      properties:
        eventType:
          $ref: '#/components/schemas/EventType'
        immediateFlag:
          type: boolean
        locationReportingConfiguration:
          $ref: '#/components/schemas/LocationReportingConfiguration'
        lossConnectivityConfiguration:
          $ref: '#/components/schemas/LossConnectivityConfiguration'
        reachabilityForDataConfiguration:
          $ref: '#/components/schemas/ReachabilityForDataConfiguration'

    MonitoringReport:
      type: object
      required:
        - referenceId
        - eventType
        - timeStamp
      properties:
        referenceId:
          $ref: '#/components/schemas/ReferenceId'
        eventType:
          $ref: '#/components/schemas/EventType'
        timeStamp:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/DateTime'
        report:
          $ref: '#/components/schemas/Report'

    ReportingOptions:
      type: object
      properties:
        maxNumOfReports:
          $ref: '#/components/schemas/MaxNumOfReports'
        expiry:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/DateTime'
        reportPeriod:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/DurationSec'

    Report:
      type: object
      properties:
        reachabilityForSmsReport:
          $ref: '#/components/schemas/ReachabilityForSmsReport'

    ReachabilityForSmsReport:
      type: object
      required:
        - reachabilitySmsStatus
      properties:
        reachabilitySmsStatus:
          type: boolean
        maxAvailabilityTime:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/DateTime'

    LossConnectivityConfiguration:
      type: object
      properties:
        maxDetectionTime:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/DurationSec'

    LocationReportingConfiguration:
      type: object
      required:
        - currentLocation
      properties:
        currentLocation:
          type: boolean
        accuracy:
          $ref: '#/components/schemas/LocationAccuracy'
    ReachabilityForDataConfiguration:
      type: object
      anyOf:
        - required: [ maximumLatency ]
        - required: [ maximumResponseTime ]
        - required: [ suggestedPacketNumDl ]
      properties:
        maximumLatency:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/DurationSec'
        maximumResponseTime:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/DurationSec'
        suggestedPacketNumDl:
          type: integer
          minimum: 1

# SIMPLE TYPES:

    ReferenceId:
      type: integer

    Imsi:
      type: string
      pattern: '^(imsi-[0-9]{5,15})$'

    MaxNumOfReports:
      type: integer
      minimum: 1

# ENUMS:

    EventType:
      anyOf:
        - type: string
          enum:
          - LOSS_OF_CONNECTIVITY
          - UE_REACHABILITY_FOR_DATA
          - UE_REACHABILITY_FOR_SMS
          - LOCATION_REPORTING
          - COMMUNICATION_FAILURE
          - AVAILABILITY_AFTER_DDN_FAILURE
          - PDN_CONNECTIVITY_STATUS
        - type: string

    LocationAccuracy:
      anyOf:
        - type: string
          enum:
          - CELL_LEVEL
          - TA_LEVEL
        - type: string
