openapi: 3.0.0
info:
  title: 'UPF Event Exposure Service'
  version: 1.0.0
  description: |
    UPF Event Exposure Service.  
    © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).  
    All rights reserved.
externalDocs:
  description: 3GPP TS 29.564 V17.1.0; 5G System; User Plane Function Services; Stage 3.
  url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.564/
servers:
  - url: '{apiRoot}/nupf-ee/v1'
    variables:
      apiRoot:
        default: https://example.com
        description: apiRoot as defined in clause 4.4 of 3GPP TS 29.501
paths:
  /ee-subscriptions:
    post:
    # This is a pseudo operation, clients shall NOT invoke this method!
      summary: subscribe to notifications
      operationId: CreateIndividualSubcription
      tags:
        - Subscriptions (Collection)
      requestBody:
        required: true
        content:
          application/json:
            schema: {}
      responses:
        default:
          $ref: 'TS29571_CommonData.yaml#/components/responses/default'
      callbacks:
        eeNotification:
          '{eventNotificationUri}':
          # The URI in {eventNotificationUri} is provided via N4 interface during provisioning of Session Reporting Rule.
            post:
              requestBody:
                required: true
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/NotificationData'
              responses:
                '204':
                  description: No Content, Notification was succesfull
                '307':
                  description: Temporary Redirect
                  content:
                    application/json:
                      schema:
                        $ref: 'TS29571_CommonData.yaml#/components/schemas/RedirectResponse'
                  headers:
                    Location:
                      description: 'The URI pointing to the resource located on the redirect target NF service consumer'
                      required: true
                      schema:
                        type: string
                '308':
                  description: Permanent Redirect
                  content:
                    application/json:
                      schema:
                        $ref: 'TS29571_CommonData.yaml#/components/schemas/RedirectResponse'
                  headers:
                    Location:
                      description: 'The URI pointing to the resource located on the redirect target NF service consumer'
                      required: true
                      schema:
                        type: string
                '404':
                  $ref: 'TS29571_CommonData.yaml#/components/responses/404'
                default:
                  $ref: 'TS29571_CommonData.yaml#/components/responses/default'

components:
  schemas:
    # API specific definitions
# STRUCTURED DATA TYPES

    NotificationData:
      type: object
      required:
        - notificationItems
      properties:
        notificationItems:
          type: array
          items:
            $ref: '#/components/schemas/NotificationItem'
          minItems: 1
        correlationId:
          type: string

    NotificationItem:
      type: object
      required:
        - eventType
        - timeStamp
      anyOf:
        - required: [ ueIpv4Addr ]
        - required: [ ueIpv6Prefix ]
      properties:
        eventType:
          $ref: '#/components/schemas/EventType'
        ueIpv4Addr:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/Ipv4Addr'
        ueIpv6Prefix:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/Ipv6Prefix'
        dnn:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/Dnn'
        snssai:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/Snssai'
        gpsi:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/Gpsi'
        timeStamp:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/DateTime'
        startTime:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/DateTime'
        qosMonitoringMeasurement:
          $ref: '#/components/schemas/QosMonitoringMeasurement'

    QosMonitoringMeasurement:
      type: object
      properties:
        dlPacketDelay:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/Uint32'
        ulPacketDelay:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/Uint32'
        rtrPacketDelay:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/Uint32'

# ENUMS

    EventType:
      anyOf:
        - type: string
          enum:
          - QOS_MONITORING
        - type: string

# SIMPLE TYPES
