openapi: 3.0.0

info:
  version: 1.2.0-alpha.2
  title: VAE_DynamicGroup
  description: |
    VAE_Dynamic_Group Service  
    © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).  
    All rights reserved.

externalDocs:
  description: 3GPP TS 29.486 V18.1.0 V2X Application Enabler (VAE) Services
  url: 'https://www.3gpp.org/ftp/Specs/archive/29_series/29.486/'

security:
  - {}
  - oAuth2ClientCredentials: []

servers:
  - url: '{apiRoot}/vae-dynamic-group/v1'
    variables:
      apiRoot:
        default: https://example.com
        description: apiRoot as defined in clause 4.4 of 3GPP TS 29.501

paths:
  /group-configurations:
    post:
      summary: VAE_Dynamice_Group resource create service Operation
      tags:
        - application requirements collection (Document)
      operationId: CreateGroupConfiguration
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GroupConfigurationData'
        required: true
      responses:
        '201':
          description: Application Requirement Resource created
          headers:
            Location:
              description: Contains the URI of the newly created resource.
              required: true
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GroupConfigurationData'
        '400':
          $ref: 'TS29571_CommonData.yaml#/components/responses/400'
        '401':
          $ref: 'TS29571_CommonData.yaml#/components/responses/401'
        '403':
          $ref: 'TS29571_CommonData.yaml#/components/responses/403'
        '404':
          $ref: 'TS29571_CommonData.yaml#/components/responses/404'
        '411':
          $ref: 'TS29571_CommonData.yaml#/components/responses/411'
        '413':
          $ref: 'TS29571_CommonData.yaml#/components/responses/413'
        '415':
          $ref: 'TS29571_CommonData.yaml#/components/responses/415'
        '429':
          $ref: 'TS29571_CommonData.yaml#/components/responses/429'
        '500':
          $ref: 'TS29571_CommonData.yaml#/components/responses/500'
        '503':
          $ref: 'TS29571_CommonData.yaml#/components/responses/503'
        default:
          $ref: 'TS29571_CommonData.yaml#/components/responses/default'
      callbacks:
        NotifyDynamicGroup:
          '{$request.body#/notifUri}':
            post:
              requestBody:
                required: true
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/DynamicGroupNotification'
              responses:
                '204':
                  description: No Content, notification was succesfull
                '307':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/307'
                '308':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/308'
                '400':
                  $ref: 'TS29571_CommonData.yaml#/components/responses/400'
                '401':
                  $ref: 'TS29571_CommonData.yaml#/components/responses/401'
                '403':
                  $ref: 'TS29571_CommonData.yaml#/components/responses/403'
                '404':
                  $ref: 'TS29571_CommonData.yaml#/components/responses/404'
                '411':
                  $ref: 'TS29571_CommonData.yaml#/components/responses/411'
                '413':
                  $ref: 'TS29571_CommonData.yaml#/components/responses/413'
                '415':
                  $ref: 'TS29571_CommonData.yaml#/components/responses/415'
                '429':
                  $ref: 'TS29571_CommonData.yaml#/components/responses/429'
                '500':
                  $ref: 'TS29571_CommonData.yaml#/components/responses/500'
                '503':
                  $ref: 'TS29571_CommonData.yaml#/components/responses/503'
                default:
                  $ref: 'TS29571_CommonData.yaml#/components/responses/default'
  /group-configurations/{configId}:
    get:
      summary: VAE Group Configuration resource read service Operation
      tags:
        - Individual Group Configuration(Document)
      operationId: ReadDynamicGroupConfiguration
      parameters:
        - name: configId
          in: path
          description: Identifier of an group configuration resource.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK. Resource representation is returned.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GroupConfigurationData'
        '307':
          $ref: 'TS29122_CommonData.yaml#/components/responses/307'
        '308':
          $ref: 'TS29122_CommonData.yaml#/components/responses/308'
        '400':
          $ref: 'TS29571_CommonData.yaml#/components/responses/400'
        '401':
          $ref: 'TS29571_CommonData.yaml#/components/responses/401'
        '403':
          $ref: 'TS29571_CommonData.yaml#/components/responses/403'
        '404':
          $ref: 'TS29571_CommonData.yaml#/components/responses/404'
        '406':
          $ref: 'TS29571_CommonData.yaml#/components/responses/406'
        '429':
          $ref: 'TS29571_CommonData.yaml#/components/responses/429'
        '500':
          $ref: 'TS29571_CommonData.yaml#/components/responses/500'
        '503':
          $ref: 'TS29571_CommonData.yaml#/components/responses/503'
        default:
          $ref: 'TS29571_CommonData.yaml#/components/responses/default'
    delete:
      summary: VAE Group Configuration resource delete service Operation
      tags:
        - Individual group configuration (Document)
      operationId: DeleteGroupConfiguration
      parameters:
        - name: configId
          in: path
          required: true
          description: Unique ID of the group configuration to be deleted.
          schema:
            type: string
      responses:
        '204':
          description: The subscription was terminated successfully.
        '307':
          $ref: 'TS29122_CommonData.yaml#/components/responses/307'
        '308':
          $ref: 'TS29122_CommonData.yaml#/components/responses/308'
        '400':
          $ref: 'TS29571_CommonData.yaml#/components/responses/400'
        '401':
          $ref: 'TS29571_CommonData.yaml#/components/responses/401'
        '403':
          $ref: 'TS29571_CommonData.yaml#/components/responses/403'
        '404':
          $ref: 'TS29571_CommonData.yaml#/components/responses/404'
        '429':
          $ref: 'TS29571_CommonData.yaml#/components/responses/429'
        '500':
          $ref: 'TS29571_CommonData.yaml#/components/responses/500'
        '503':
          $ref: 'TS29571_CommonData.yaml#/components/responses/503'
        default:
          $ref: 'TS29571_CommonData.yaml#/components/responses/default'

components:
  securitySchemes:
    oAuth2ClientCredentials:
      type: oauth2
      flows: 
        clientCredentials:
          tokenUrl: '{tokenUrl}'
          scopes: {}

  schemas:
    GroupConfigurationData:
      description: Represents an individual Group Configuration resource for a V2X group ID.
      type: object
      properties:
        groupId:
          $ref: 'TS29486_VAE_MessageDelivery.yaml#/components/schemas/V2xGroupId'
        definition:
          type: string
        leaderId:
          $ref: 'TS29486_VAE_MessageDelivery.yaml#/components/schemas/V2xUeId'
        notifUri:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/Uri'
        duration:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/DateTime'
        requestTestNotification:
          type: boolean
          description: >
            Set to true by the service consumer to request the VAE server to test
            a notification connection. Set to false or omitted otherwise.
        websockNotifConfig:
          $ref: 'TS29122_CommonData.yaml#/components/schemas/WebsockNotifConfig'
        suppFeat:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/SupportedFeatures'
      required:
        - groupId
        - definition
        - leaderId
        - notifUri

    DynamicGroupNotification:
      description: >
        Represents a notification on the dynamic group information (i.e. group member
        joins or leaves).
      type: object
      properties:
        resourceUri:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/Uri'
        joinedUeIds:
          type: array
          items:
            $ref: 'TS29486_VAE_MessageDelivery.yaml#/components/schemas/V2xUeId'
          minItems: 1
        leftUeIds:
          type: array
          items:
            $ref: 'TS29486_VAE_MessageDelivery.yaml#/components/schemas/V2xUeId'
          minItems: 1
      required:
        - resourceUri
