openapi: 3.0.0

info:
  title: MSGG_BGDelivery
  version: 1.0.0-alpha.2
  description: |
    API for Broadcast Message Delivery Service.  
    © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).  
    All rights reserved.

externalDocs:
  description: >
    3GPP TS 29.538 V18.4.0; Enabling MSGin5G Service; Application Programming Interfaces (API)
    specification; Stage 3
  url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.538/

servers:
  - url: '{apiRoot}/msgg-bgdelivery/v1'
    variables:
      apiRoot:
        default: https://example.com
        description: apiRoot as defined in clause 4.4 of 3GPP TS 29.501

security:
  - {}
  - oAuth2ClientCredentials: []

paths:
  /deliver-message:
    post:
      summary: deliver message to Broadcast Message Gateway
      tags:
        - Broadcast Message delivery
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BgMessageDelivery'
      responses:
        '204':
          description: No Content, Message delivery successful
        '400':
          $ref: 'TS29571_CommonData.yaml#/components/responses/400'
        '401':
          $ref: 'TS29571_CommonData.yaml#/components/responses/401'
        '403':
          $ref: 'TS29571_CommonData.yaml#/components/responses/403'
        '404':
          $ref: 'TS29571_CommonData.yaml#/components/responses/404'
        '411':
          $ref: 'TS29571_CommonData.yaml#/components/responses/411'
        '413':
          $ref: 'TS29571_CommonData.yaml#/components/responses/413'
        '415':
          $ref: 'TS29571_CommonData.yaml#/components/responses/415'
        '429':
          $ref: 'TS29571_CommonData.yaml#/components/responses/429'
        '500':
          $ref: 'TS29571_CommonData.yaml#/components/responses/500'
        '503':
          $ref: 'TS29571_CommonData.yaml#/components/responses/503'
        default:
          $ref: 'TS29571_CommonData.yaml#/components/responses/default'


components:
  securitySchemes:
    oAuth2ClientCredentials:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: '{tokenUrl}'
          scopes: {}


  schemas:
#
# STRUCTURED DATA TYPES
#
    BgMessageDelivery:
      description: Broadcast message delivery data
      type: object
      required:
        - oriAddr
        - destAddr
        - msgId
      properties:
        oriAddr:
          $ref: 'TS29538_MSGG_L3GDelivery.yaml#/components/schemas/Address'
        destAddr:
          $ref: 'TS29538_MSGG_L3GDelivery.yaml#/components/schemas/Address'
        appId:
          type: string
        msgId:
          type: string
        delivStReqInd:
          type: boolean
        payload:
          type: string
        segInd:
          type: boolean
        segParams:
          $ref: 'TS29538_MSGS_MSGDelivery.yaml#/components/schemas/MessageSegmentParameters'
        priority:
          $ref: 'TS29538_MSGS_MSGDelivery.yaml#/components/schemas/Priority'
