openapi: 3.0.0

info:
  title: Nnssaaf_AIW
  version: 1.1.0-alpha.2
  description: |
    AAA Interworking Authentication and Authorization Service.  
    © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).  
    All rights reserved.

externalDocs:
  description: 3GPP TS29.526, NSSAA Service, version 18.3.0.
  url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.526/

servers:
  - url: '{apiRoot}/nnssaaf-aiw/v1'
    variables:
      apiRoot:
        default: https://example.com
        description: apiRoot as defined in clause 4.4 of 3GPP TS 29.501

security:
  - {}
  - oAuth2ClientCredentials:
    - nnssaaf-aiw

paths:
  /authentications:
    post:
      summary: Create authentication context
      operationId: CreateAuthenticationContext
      tags:
        - Authentications (Collections)
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthInfo'
        required: true
      responses:
        '201':
          description: AuthContext successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthContext'
          headers:
            Location:
              description: 'Contains the URI of the newly created resource according to the structure: {apiRoot}/nnssaaf-aiw/<apiVersion>/authentications/{authCtxId}'
              required: true
              schema:
                type: string
        '307':
          $ref: 'TS29571_CommonData.yaml#/components/responses/307'
        '308':
          $ref: 'TS29571_CommonData.yaml#/components/responses/308'
        '400':
          $ref: 'TS29571_CommonData.yaml#/components/responses/400'
        '401':
          $ref: 'TS29571_CommonData.yaml#/components/responses/401'
        '403':
          $ref: 'TS29571_CommonData.yaml#/components/responses/403'
        '404':
          $ref: 'TS29571_CommonData.yaml#/components/responses/404'
        '411':
          $ref: 'TS29571_CommonData.yaml#/components/responses/411'
        '413':
          $ref: 'TS29571_CommonData.yaml#/components/responses/413'
        '415':
          $ref: 'TS29571_CommonData.yaml#/components/responses/415'
        '429':
          $ref: 'TS29571_CommonData.yaml#/components/responses/429'
        '500':
          $ref: 'TS29571_CommonData.yaml#/components/responses/500'
        '502':
          $ref: 'TS29571_CommonData.yaml#/components/responses/502'
        '503':
          $ref: 'TS29571_CommonData.yaml#/components/responses/503'
        '504':
          $ref: 'TS29571_CommonData.yaml#/components/responses/504'

  /authentications/{authCtxId}:
    put:
      summary: Confirm the authentication result
      operationId: ConfirmAuthentication
      tags:
        - Authentication (Document)
      parameters:
        - name: authCtxId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthConfirmationData'
      responses:
        '200':
          description: Request processed (EAP success or Failure)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthConfirmationResponse'
        '307':
          $ref: 'TS29571_CommonData.yaml#/components/responses/307'
        '308':
          $ref: 'TS29571_CommonData.yaml#/components/responses/308'
        '400':
          $ref: 'TS29571_CommonData.yaml#/components/responses/400'
        '401':
          $ref: 'TS29571_CommonData.yaml#/components/responses/401'
        '403':
          $ref: 'TS29571_CommonData.yaml#/components/responses/403'
        '404':
          $ref: 'TS29571_CommonData.yaml#/components/responses/404'
        '411':
          $ref: 'TS29571_CommonData.yaml#/components/responses/411'
        '413':
          $ref: 'TS29571_CommonData.yaml#/components/responses/413'
        '415':
          $ref: 'TS29571_CommonData.yaml#/components/responses/415'
        '429':
          $ref: 'TS29571_CommonData.yaml#/components/responses/429'
        '500':
          $ref: 'TS29571_CommonData.yaml#/components/responses/500'
        '502':
          $ref: 'TS29571_CommonData.yaml#/components/responses/502'
        '503':
          $ref: 'TS29571_CommonData.yaml#/components/responses/503'
        '504':
          $ref: 'TS29571_CommonData.yaml#/components/responses/504'

components:
  securitySchemes:
    oAuth2ClientCredentials:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: '{nrfApiRoot}/oauth2/token'
          scopes:
            nnssaaf-aiw: Access to the nnssaaf-aiw API

  schemas:

#
# COMPLEX TYPES:
#

    AuthInfo:
      type: object
      properties:
        supi:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/Supi'
        eapIdRsp:
          $ref: 'TS29526_Nnssaaf_NSSAA.yaml#/components/schemas/EapMessage'
        ttlsInnerMethodContainer:
          $ref: 'TS29526_Nnssaaf_NSSAA.yaml#/components/schemas/EapMessage'
        supportedFeatures:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/SupportedFeatures'
      required:
        - supi

    AuthContext:
      type: object
      properties:
        supi:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/Supi'
        authCtxId:
          $ref: '#/components/schemas/AuthCtxId'
        eapMessage:
          $ref: 'TS29526_Nnssaaf_NSSAA.yaml#/components/schemas/EapMessage'
        ttlsInnerMethodContainer:
          $ref: 'TS29526_Nnssaaf_NSSAA.yaml#/components/schemas/EapMessage'
        supportedFeatures:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/SupportedFeatures'
      required:
        - supi
        - authCtxId

    AuthConfirmationData:
      type: object
      properties:
        supi:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/Supi'
        eapMessage:
          $ref: 'TS29526_Nnssaaf_NSSAA.yaml#/components/schemas/EapMessage'
        supportedFeatures:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/SupportedFeatures'
      required:
        - supi
        - eapMessage

    AuthConfirmationResponse:
      type: object
      properties:
        supi:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/Supi'
        eapMessage:
          $ref: 'TS29526_Nnssaaf_NSSAA.yaml#/components/schemas/EapMessage'
        authResult:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/AuthStatus'
        pvsInfo:
          type: array
          items:
            $ref: 'TS29571_CommonData.yaml#/components/schemas/ServerAddressingInfo'
          minItems: 1
        msk:
          $ref: 'TS29509_Nausf_UEAuthentication.yaml#/components/schemas/Msk'
        supportedFeatures:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/SupportedFeatures'
      required:
        - supi
        - eapMessage

#
# SIMPLE TYPES:
#

    AuthCtxId:
      type: string
      description: contains the resource ID of authentication context
      nullable: false

#
# ENUMS:
#
