openapi: 3.0.0
info:
  title: EES ACR Management Event_API
  description: |
    API for EES ACR Management Event.  
    © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).  
    All rights reserved.
  version: 1.0.0-alpha.2
externalDocs:
  description: >
    3GPP TS 29.558 V1.4.0 Enabling Edge Applications;
    Application Programming Interface (API) specification; Stage 3
  url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.558/
servers:
  - url: '{apiRoot}/eees-acrmgntevent/v1'
    variables:
      apiRoot:
        default: https://example.com
        description: apiRoot as defined in clause 7.5 of 3GPP TS 29.558.

paths:
  /subscriptions:
    post:
      description: Create an Individual ACR Management Event Subscription resource.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AcrMgntEventsSubscription'
      callbacks:
        ACRManagementEventsNotification:
          '{request.body#/notificationDestination}':
            post:
              requestBody:  # contents of the callback message
                required: true
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/AcrMgntEventsNotification'
              responses:
                '204':
                  description: No Content (successful notification)
                '307':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/307'
                '308':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/308'
                '400':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/400'
                '401':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/401'
                '403':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/403'
                '404':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/404'
                '411':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/411'
                '413':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/413'
                '415':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/415'
                '429':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/429'
                '500':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/500'
                '503':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/503'
                default:
                  $ref: 'TS29122_CommonData.yaml#/components/responses/default'
      responses:
        '201':
          description: Created (Successful creation)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AcrMgntEventsSubscription'
          headers:
            Location:
              description: 'Contains the URI of the newly created resource'
              required: true
              schema:
                type: string
        '204':
          description: Successful case. The resource has been successfully created and no additional content is to be sent in the response message.
        '400':
          $ref: 'TS29122_CommonData.yaml#/components/responses/400'
        '401':
          $ref: 'TS29122_CommonData.yaml#/components/responses/401'
        '403':
          $ref: 'TS29122_CommonData.yaml#/components/responses/403'
        '404':
          $ref: 'TS29122_CommonData.yaml#/components/responses/404'
        '411':
          $ref: 'TS29122_CommonData.yaml#/components/responses/411'
        '413':
          $ref: 'TS29122_CommonData.yaml#/components/responses/413'
        '415':
          $ref: 'TS29122_CommonData.yaml#/components/responses/415'
        '429':
          $ref: 'TS29122_CommonData.yaml#/components/responses/429'
        '500':
          $ref: 'TS29122_CommonData.yaml#/components/responses/500'
        '503':
          $ref: 'TS29122_CommonData.yaml#/components/responses/503'
        default:
          $ref: 'TS29122_CommonData.yaml#/components/responses/default'

    get:
      description: Retrieve all the ACR Management Events Subscriptions information.
      parameters:
        - name: supp-feat
          in: query
          description: Features supported by the EAS.
          required: false
          schema:
            $ref: 'TS29571_CommonData.yaml#/components/schemas/SupportedFeatures'
      responses:
        '200':
          description: OK (Successful get all of the active subscriptions)
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AcrMgntEventsSubscription'
                minItems: 1
                description: All the active ACR management events subscriptions
        '307':
          $ref: 'TS29122_CommonData.yaml#/components/responses/307'
        '308':
          $ref: 'TS29122_CommonData.yaml#/components/responses/308'
        '400':
          $ref: 'TS29122_CommonData.yaml#/components/responses/400'
        '401':
          $ref: 'TS29122_CommonData.yaml#/components/responses/401'
        '403':
          $ref: 'TS29122_CommonData.yaml#/components/responses/403'
        '404':
          $ref: 'TS29122_CommonData.yaml#/components/responses/404'
        '406':
          $ref: 'TS29122_CommonData.yaml#/components/responses/406'
        '429':
          $ref: 'TS29122_CommonData.yaml#/components/responses/429'
        '500':
          $ref: 'TS29122_CommonData.yaml#/components/responses/500'
        '503':
          $ref: 'TS29122_CommonData.yaml#/components/responses/503'
        default:
          $ref: 'TS29122_CommonData.yaml#/components/responses/default'

  /subscriptions/{subscriptionId}:
    get:
      description: Retrieve an Individual ACR Management Events Subscription.
      parameters:
        - name: subscriptionId
          in: path
          description: Subscription Id.
          required: true
          schema:
            type: string
        - name: supp-feat
          in: query
          description: Features supported by the EAS.
          required: false
          schema:
            $ref: 'TS29571_CommonData.yaml#/components/schemas/SupportedFeatures'
      responses:
        '200':
          description: OK (Successful get the active subscription).
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AcrMgntEventsSubscription'
        '307':
          $ref: 'TS29122_CommonData.yaml#/components/responses/307'
        '308':
          $ref: 'TS29122_CommonData.yaml#/components/responses/308'
        '400':
          $ref: 'TS29122_CommonData.yaml#/components/responses/400'
        '401':
          $ref: 'TS29122_CommonData.yaml#/components/responses/401'
        '403':
          $ref: 'TS29122_CommonData.yaml#/components/responses/403'
        '404':
          $ref: 'TS29122_CommonData.yaml#/components/responses/404'
        '406':
          $ref: 'TS29122_CommonData.yaml#/components/responses/406'
        '429':
          $ref: 'TS29122_CommonData.yaml#/components/responses/429'
        '500':
          $ref: 'TS29122_CommonData.yaml#/components/responses/500'
        '503':
          $ref: 'TS29122_CommonData.yaml#/components/responses/503'
        default:
          $ref: 'TS29122_CommonData.yaml#/components/responses/default'
    put:
      description: Fully replace an existing Individual ACR Management Events Subscription.
      parameters:
        - name: subscriptionId
          in: path
          description: Subscription Id.
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AcrMgntEventsSubscription'
      responses:
        '200':
          description: OK (Successful get the active subscription).
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AcrMgntEventsSubscription'
        '204':
          description: No Content
        '307':
          $ref: 'TS29122_CommonData.yaml#/components/responses/307'
        '308':
          $ref: 'TS29122_CommonData.yaml#/components/responses/308'
        '400':
          $ref: 'TS29122_CommonData.yaml#/components/responses/400'
        '401':
          $ref: 'TS29122_CommonData.yaml#/components/responses/401'
        '403':
          $ref: 'TS29122_CommonData.yaml#/components/responses/403'
        '404':
          $ref: 'TS29122_CommonData.yaml#/components/responses/404'
        '411':
          $ref: 'TS29122_CommonData.yaml#/components/responses/411'
        '413':
          $ref: 'TS29122_CommonData.yaml#/components/responses/413'
        '415':
          $ref: 'TS29122_CommonData.yaml#/components/responses/415'
        '429':
          $ref: 'TS29122_CommonData.yaml#/components/responses/429'
        '500':
          $ref: 'TS29122_CommonData.yaml#/components/responses/500'
        '503':
          $ref: 'TS29122_CommonData.yaml#/components/responses/503'
        default:
          $ref: 'TS29122_CommonData.yaml#/components/responses/default'
    patch:
      parameters:
        - name: subscriptionId
          in: path
          description: Subscription Id.
          required: true
          schema:
            type: string
      requestBody:
        description: Partial update an existing Individual ACR Management Events Subscription.
        required: true
        content:
          application/merge-patch+json:
            schema:
              $ref: '#/components/schemas/AcrMgntEventsSubscriptionPatch'
      responses:
        '200':
          description: The Individual ACR Management Events Subscription is successfully modified and the updated subscription information is returned in the response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AcrMgntEventsSubscription'
        '204':
          description: No Content.
        '307':
          $ref: 'TS29122_CommonData.yaml#/components/responses/307'
        '308':
          $ref: 'TS29122_CommonData.yaml#/components/responses/308'
        '400':
          $ref: 'TS29122_CommonData.yaml#/components/responses/400'
        '401':
          $ref: 'TS29122_CommonData.yaml#/components/responses/401'
        '403':
          $ref: 'TS29122_CommonData.yaml#/components/responses/403'
        '404':
          $ref: 'TS29122_CommonData.yaml#/components/responses/404'
        '411':
          $ref: 'TS29122_CommonData.yaml#/components/responses/411'
        '413':
          $ref: 'TS29122_CommonData.yaml#/components/responses/413'
        '415':
          $ref: 'TS29122_CommonData.yaml#/components/responses/415'
        '429':
          $ref: 'TS29122_CommonData.yaml#/components/responses/429'
        '500':
          $ref: 'TS29122_CommonData.yaml#/components/responses/500'
        '503':
          $ref: 'TS29122_CommonData.yaml#/components/responses/503'
        default:
          $ref: 'TS29122_CommonData.yaml#/components/responses/default'
    delete:
      description: Delete an existing Individual ACR Management Events Subscription.
      parameters:
        - name: subscriptionId
          in: path
          description: Subscription Id.
          required: true
          schema:
            type: string
      responses:
        '204':
          description: The individual subscription is deleted.
        '307':
          $ref: 'TS29122_CommonData.yaml#/components/responses/307'
        '308':
          $ref: 'TS29122_CommonData.yaml#/components/responses/308'
        '400':
          $ref: 'TS29122_CommonData.yaml#/components/responses/400'
        '401':
          $ref: 'TS29122_CommonData.yaml#/components/responses/401'
        '403':
          $ref: 'TS29122_CommonData.yaml#/components/responses/403'
        '404':
          $ref: 'TS29122_CommonData.yaml#/components/responses/404'
        '429':
          $ref: 'TS29122_CommonData.yaml#/components/responses/429'
        '500':
          $ref: 'TS29122_CommonData.yaml#/components/responses/500'
        '503':
          $ref: 'TS29122_CommonData.yaml#/components/responses/503'
        default:
          $ref: 'TS29122_CommonData.yaml#/components/responses/default'

# Components

components:
  schemas:
    AcrMgntEventsSubscription:
      type: object
      description: Represents an Individual ACR Management Events Subscription.
      properties:
        self:
          $ref: 'TS29122_CommonData.yaml#/components/schemas/Uri'
        easId:
          type: string
          description: Identifier of an EAS.
        tgtUeId:
          $ref: '#/components/schemas/TargetUeIdentification'
        eventSubscs:
          type: array
          items:
            $ref: '#/components/schemas/AcrMgntEventSubsc'
          minItems: 1
          description: The subscribed ACR management events.
        evtReq:
          $ref: 'TS29523_Npcf_EventExposure.yaml#/components/schemas/ReportingInformation'
        notificationDestination:
          $ref: 'TS29122_CommonData.yaml#/components/schemas/Uri'
        dnaiChgType:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/DnaiChangeType'
        easAckInd:
          type: boolean
        eventReports:
          type: array
          items:
            $ref: '#/components/schemas/AcrMgntEventReport'
          minItems: 1
          description: The ACR management event report(s).
        easChars:
          type: array
          items:
            $ref: 'TS24558_Eees_EASDiscovery.yaml#/components/schemas/EasCharacteristics'
          minItems: 1
          description: A list of EAS characteristics.
        failEventReports:
          type: array
          items:
            $ref: '#/components/schemas/FailureAcrMgntEventInfo'
          minItems: 1
          description: Failure event reports.
        requestTestNotification:
          type: boolean
          description: Set to true by the EAS to request the EES to send a test notification. Set to false or omitted otherwise.
        websockNotifConfig:
          $ref: 'TS29122_CommonData.yaml#/components/schemas/WebsockNotifConfig'
        suppFeat:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/SupportedFeatures'
      required:
        - easId
        - tgtUeId
        - eventSubscs
        - notificationDestination
    AcrMgntEventSubsc:
      type: object
      description: Represents an ACR Management Event Subscription.
      properties:
        event:
          $ref: '#/components/schemas/AcrMgntEvent'
        eventFilter:
          $ref: '#/components/schemas/AcrMgntEventFilter'
      required:
        - event
        - eventFilter
    AcrMgntEventsSubscriptionPatch:
      type: object
      description: Represents a modification request of Individual ACR Management Events Subscription.
      properties:
        eventSubscs:
          type: array
          items:
            $ref: '#/components/schemas/AcrMgntEventSubsc'
          minItems: 1
          description: The subscribed ACR management events.
        evtReq:
          $ref: 'TS29523_Npcf_EventExposure.yaml#/components/schemas/ReportingInformation'
        notificationDestination:
          $ref: 'TS29122_CommonData.yaml#/components/schemas/Uri'
        dnaiChgType:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/DnaiChangeTypeRm'
        easAckInd:
          type: boolean
        easChars:
          type: array
          items:
            $ref: 'TS24558_Eees_EASDiscovery.yaml#/components/schemas/EasCharacteristics'
          minItems: 1
          description: A list of EAS characteristics.

    AcrMgntEventFilter:
      type: string
# Editor’s Note: Definition of AcrMgntEventFilter data type is FFS.
    AcrMgntEventsNotification:
      type: object
      description: Represents the ACR management events notification.
      properties:
        subpId:
          type: string
          description: String identifying the Individual ACR Management Events Subscription for which the notification is delivered.
        eventReports:
          type: array
          items:
            $ref: '#/components/schemas/AcrMgntEventReport'
          minItems: 1
          description: A list of ACR management event reports.
      required:
        - subpId
        - eventReports
    AcrMgntEventReport:
      type: object
      description: Represents an ACR management event report.
      properties:
        event:
          $ref: '#/components/schemas/AcrMgntEvent'
        timeStamp:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/DateTime'
        upPathChgInfo:
          $ref: '#/components/schemas/UpPathChangeInfo'
        easEndPoint:
          type: string
# Editor’s Note: the reference for the EndPoint data tye is defined in Eees_EASRegistration API, and will be updated later.
      required:
        - event
    FailureAcrMgntEventInfo:
      type: object
      description: Represents a failure ACR management event.
      properties:
        event:
          $ref: '#/components/schemas/AcrMgntEvent'
        failureCode:
          $ref: '#/components/schemas/AcrMgntEventFailureCode'
      required:
        - event
        - failureCode
    TargetUeIdentification:
      description: Identifies the target UE information.
      type: object
      properties:
        gpsi:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/Gpsi'
        intGrpId:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/GroupId'
        extGrpId:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/ExternalGroupId'
        ueIpAddr:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/IpAddr'

    AcrMgntEventFailureCode:
      type: string
# Editor’s Note: Definition of AcrMgntEventFailureCode data type is FFS.
    UpPathChangeInfo:
      type: string
# Editor’s Note: Definition of UpPathChangeInfo data type is FFS.
    AcrMgntEvent:
      anyOf:
      - type: string
        enum:
          - UP_PATH_CHG
          - ACR_MONITORING
          - ACR_FACILITATION
      - type: string
        description: >
          This string provides forward-compatibility with future
          extensions to the enumeration but is not used to encode
          content defined in the present version of this API.
      description: >
        Possible values are
        - UP_PATH_CHG: User plane path change event.
        - ACR_MONITORING: ACR monitoring event.
        - ACR_FACILITATION: ACR facilitation event.
