openapi: 3.0.0
info:
  title: EES EEL Managed ACR Service
  version: 1.1.0-alpha.2
  description: |
    EES EEL Managed ACR Service.  
    © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).  
    All rights reserved.

externalDocs:
  description: >
    3GPP TS 29.558 V18.1.0; Enabling Edge Applications;
    Application Programming Interface (API) specification; Stage 3.
  url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.558/
security:
  - {}
  - oAuth2ClientCredentials: []
servers:
  - url: '{apiRoot}/eees-eel-acr/v1'
    variables:
      apiRoot:
        default: https://example.com
        description: apiRoot as defined in clause 5.2.4 of 3GPP TS 29.122

paths:
  /request-eelacr:
    post:
      summary: Request the EES (e.g. S-EES) to handle all the operations of an ACR.
      operationId: RequestEELManagedACR
      tags:
        - Request EEL Managed ACR
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EELACRReq'
      responses:
        '200':
          description: >
            The requested EEL Managed ACR initiation was successfully received and
            processed. The response body contains the feedback of the EES.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EELACRResp'
        '307':
          $ref: 'TS29122_CommonData.yaml#/components/responses/307'
        '308':
          $ref: 'TS29122_CommonData.yaml#/components/responses/308'
        '400':
          $ref: 'TS29122_CommonData.yaml#/components/responses/400'
        '401':
          $ref: 'TS29122_CommonData.yaml#/components/responses/401'
        '403':
          $ref: 'TS29122_CommonData.yaml#/components/responses/403'
        '404':
          $ref: 'TS29122_CommonData.yaml#/components/responses/404'
        '411':
          $ref: 'TS29122_CommonData.yaml#/components/responses/411'
        '413':
          $ref: 'TS29122_CommonData.yaml#/components/responses/413'
        '415':
          $ref: 'TS29122_CommonData.yaml#/components/responses/415'
        '429':
          $ref: 'TS29122_CommonData.yaml#/components/responses/429'
        '500':
          $ref: 'TS29122_CommonData.yaml#/components/responses/500'
        '503':
          $ref: 'TS29122_CommonData.yaml#/components/responses/503'
        default:
          $ref: 'TS29122_CommonData.yaml#/components/responses/default'

  /subscriptions:
    get:
      summary: Retrieve all the active ACT Status Subscriptions managed by the EES.
      operationId: GetACTStatusSubscriptions
      tags:
        - ACT Status Subscriptions (Collection)
      responses:
        '200':
          description: >
            OK. All the active ACT status subscriptions managed by the EES shall
            be returned.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ACTStatusSubsc'
        '307':
          $ref: 'TS29122_CommonData.yaml#/components/responses/307'
        '308':
          $ref: 'TS29122_CommonData.yaml#/components/responses/308'
        '400':
          $ref: 'TS29122_CommonData.yaml#/components/responses/400'
        '401':
          $ref: 'TS29122_CommonData.yaml#/components/responses/401'
        '403':
          $ref: 'TS29122_CommonData.yaml#/components/responses/403'
        '404':
          $ref: 'TS29122_CommonData.yaml#/components/responses/404'
        '406':
          $ref: 'TS29122_CommonData.yaml#/components/responses/406'
        '429':
          $ref: 'TS29122_CommonData.yaml#/components/responses/429'
        '500':
          $ref: 'TS29122_CommonData.yaml#/components/responses/500'
        '503':
          $ref: 'TS29122_CommonData.yaml#/components/responses/503'
        default:
          $ref: 'TS29122_CommonData.yaml#/components/responses/default'

    post:
      summary: Request the creation of a subscription to ACT status reporting.
      operationId: CreateACTStatusSubsc
      tags:
        - ACT Status Subscriptions (Collection)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ACTStatusSubsc'
      responses:
        '201':
          description: >
            Created. The subscription is successfully created and a representation of the
            created Individual ACT Status Subscription resource shall be returned.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ACTStatusSubsc'
          headers:
            Location:
              description: >
                Contains the URI of the created Individual ACT Status Subscription resource.
              required: true
              schema:
                type: string
        '400':
          $ref: 'TS29122_CommonData.yaml#/components/responses/400'
        '401':
          $ref: 'TS29122_CommonData.yaml#/components/responses/401'
        '403':
          $ref: 'TS29122_CommonData.yaml#/components/responses/403'
        '404':
          $ref: 'TS29122_CommonData.yaml#/components/responses/404'
        '411':
          $ref: 'TS29122_CommonData.yaml#/components/responses/411'
        '413':
          $ref: 'TS29122_CommonData.yaml#/components/responses/413'
        '415':
          $ref: 'TS29122_CommonData.yaml#/components/responses/415'
        '429':
          $ref: 'TS29122_CommonData.yaml#/components/responses/429'
        '500':
          $ref: 'TS29122_CommonData.yaml#/components/responses/500'
        '503':
          $ref: 'TS29122_CommonData.yaml#/components/responses/503'
        default:
          $ref: 'TS29122_CommonData.yaml#/components/responses/default'
      callbacks:
        ACTStatusNotification:
          '{$request.body#/notificationUri}/act-status':
            post:
              requestBody:
                required: true
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/ACTStatusNotif'
              responses:
                '204':
                  description: >
                    No Content. The ACT status notification is successfully received
                    and acknowledged.
                '307':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/307'
                '308':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/308'
                '400':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/400'
                '401':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/401'
                '403':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/403'
                '404':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/404'
                '411':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/411'
                '413':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/413'
                '415':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/415'
                '429':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/429'
                '500':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/500'
                '503':
                  $ref: 'TS29122_CommonData.yaml#/components/responses/503'
                default:
                  $ref: 'TS29122_CommonData.yaml#/components/responses/default'

  /subscriptions/{subscriptionId}:
    get:
      summary: Retrieve an ACT status subscription resource.
      operationId: GetACTStatusSubscription
      tags:
        - Individual ACT Status Subscription (Document)
      parameters:
        - name: subscriptionId
          in: path
          description: Individual ACT Status Subscription identifier.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: >
            OK. The requested real-time UAV status subscription resource is returned.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ACTStatusSubsc'
        '307':
          $ref: 'TS29122_CommonData.yaml#/components/responses/307'
        '308':
          $ref: 'TS29122_CommonData.yaml#/components/responses/308'
        '400':
          $ref: 'TS29122_CommonData.yaml#/components/responses/400'
        '401':
          $ref: 'TS29122_CommonData.yaml#/components/responses/401'
        '403':
          $ref: 'TS29122_CommonData.yaml#/components/responses/403'
        '404':
          $ref: 'TS29122_CommonData.yaml#/components/responses/404'
        '406':
          $ref: 'TS29122_CommonData.yaml#/components/responses/406'
        '429':
          $ref: 'TS29122_CommonData.yaml#/components/responses/429'
        '500':
          $ref: 'TS29122_CommonData.yaml#/components/responses/500'
        '503':
          $ref: 'TS29122_CommonData.yaml#/components/responses/503'
        default:
          $ref: 'TS29122_CommonData.yaml#/components/responses/default'

components:
  securitySchemes:
    oAuth2ClientCredentials:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: '{tokenUrl}'
          scopes: {}

  schemas:
    EELACRReq:
      description: >
        Represents the parameters to request the EES (e.g. S-EES) to handle all the
        operations of an ACR.
      type: object
      properties:
        ueId:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/Gpsi'
        easCharacs:
          type: array
          items:
            $ref: 'TS24558_Eees_EASDiscovery.yaml#/components/schemas/EasCharacteristics'
          minItems: 1
        appCtxtStoreAddr:
          $ref: 'TS29122_CommonData.yaml#/components/schemas/Uri'
        suppFeat:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/SupportedFeatures'
      required:
        - ueId
        - easCharacs

    EELACRResp:
      description: Represents the feedback of the EES on EEL Managed ACR request.
      type: object
      properties:
        appCtxtStoreAddr:
          $ref: 'TS29122_CommonData.yaml#/components/schemas/Uri'
        suppFeat:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/SupportedFeatures'

    ACTStatusSubsc:
      description: >
        Represents the parameters to request the creation of a subscription to ACT
        status reporting.
      type: object
      properties:
        easId:
          type: string
          description: Contains the application identifier of the EAS, e.g. URI, FQDN.
        notificationUri:
          $ref: 'TS29122_CommonData.yaml#/components/schemas/Uri'
        suppFeat:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/SupportedFeatures'
      required:
        - easId
        - notificationUri

    ACTStatusNotif:
      description: Represents an ACT status notification.
      type: object
      properties:
        subscriptionId:
          type: string
          description: Subscription identifier.
        actStatus:
          $ref: 'TS29558_Eees_ACRStatusUpdate.yaml#/components/schemas/ACTResult'
      required:
        - subscriptionId
        - actStatus

# ENUMS:
