openapi: 3.0.0

info:
  version: '1.0.0'
  title: 'Nrouter_SMService Service API'
  description: |
    SMS Router SMService.  
    © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).  
    All rights reserved.

externalDocs:
  description: 3GPP TS 29.577 V17.0.0; 5G System; IP Short Message Gateway and SMS Router For Short Message Services; Stage 3
  url: 'https://www.3gpp.org/ftp/Specs/archive/29_series/29.577/'

security:
  - oAuth2ClientCredentials:
    - nrouter-smservice
  - {}

servers:
  - url: '{apiRoot}/nrouter-smservice/v1'
    variables:
      apiRoot:
        default: https://example.com
        description: apiRoot as defined in clause 4.4 of 3GPP TS 29.501.

paths:
  /mt-sm-infos/{gpsi}:
    put:
      summary: Create the routing information for a given UE
      operationId: RoutingInfo
      tags:
        - Creation of Routing Info
      parameters:
        - name: gpsi
          in: path
          required: true
          description: Generic Public Subscription Identifier (GPSI)
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: 'TS29577_Nipsmgw_SMService.yaml#/components/schemas/CreateRoutingData'
        required: true
      responses:
        '201':
          description: Routing Information is created in SMS Router
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreatedRoutingData'
          headers:
            Location:
              description: >
               'Contains the URI of the newly created resource, according to the structure:
               {apiRoot}/nrouter-smservice/<apiVersion>/mt-sm-infos/{gpsi}'
              required: true
              schema:
                type: string
        '200':
          description: Routing Information is updated in SMS Router
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreatedRoutingData'
        '204':
          description: Routing Information is updated in SMS Router
        '307':
          $ref: 'TS29571_CommonData.yaml#/components/responses/307'
        '308':
          $ref: 'TS29571_CommonData.yaml#/components/responses/308'
        '400':
          $ref: 'TS29571_CommonData.yaml#/components/responses/400'
        '404':
          $ref: 'TS29571_CommonData.yaml#/components/responses/404'
        '503':
          $ref: 'TS29571_CommonData.yaml#/components/responses/503'
        default:
          $ref: 'TS29571_CommonData.yaml#/components/responses/default'

  /mt-sm-infos/{gpsi}/sendsms:
    post:
      summary: Send SMS payload for a given UE
      operationId: SendSMS
      tags:
        - Send MT SMS message and the delivery report
      parameters:
        - name: gpsi
          in: path
          required: true
          description: Generic Public Subscription Identifier (GPSI)
          schema:
            type: string
      requestBody:
        content:
          multipart/related:
            schema:
              type: object
              properties:
                jsonData:
                  $ref: 'TS29577_Nipsmgw_SMService.yaml#/components/schemas/SmsData'
                binaryPayload:
                  type: string
                  format: binary
            encoding:
              jsonData:
                contentType: application/json
              binaryPayload:
                contentType: application/vnd.3gpp.sms
                headers:
                  Content-Id:
                    schema:
                      type: string
        required: true
      responses:
        '200':
          description: sending delivery report
          content:
            multipart/related:
              schema:
                $ref: 'TS29577_Nipsmgw_SMService.yaml#/components/schemas/SmsDeliveryData'
        '307':
          $ref: 'TS29571_CommonData.yaml#/components/responses/307'
        '308':
          $ref: 'TS29571_CommonData.yaml#/components/responses/308'
        '400':
          $ref: 'TS29571_CommonData.yaml#/components/responses/400'
        '404':
          $ref: 'TS29571_CommonData.yaml#/components/responses/404'
        '503':
          $ref: 'TS29571_CommonData.yaml#/components/responses/503'
        default:
          $ref: 'TS29571_CommonData.yaml#/components/responses/default'

components:

  securitySchemes:
    oAuth2ClientCredentials:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: '{nrfApiRoot}/oauth2/token'
          scopes:
            nsmsf-sms: Access to the nrouter-smservice API

  schemas:

    CreatedRoutingData:
      description: Information used for receiving the MT SMS.
      type: object
      properties:
        routerIpv4:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/Ipv4Addr'
        routerIpv6:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/Ipv6Addr'
        routerFqdn:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/Fqdn'
        supportedFeatures:
          $ref: 'TS29571_CommonData.yaml#/components/schemas/SupportedFeatures'
